-- Every profile the questionnaire draws (surprise.quiz), signed in or not, and the composed evenings
-- (surprise.parcours), readable in SQL: the evening asked, its routes, and their steps linked to the activities
-- (normalized's source_id and external_id). A redraw keeps the steps it replaces, marked replaced_at.
-- Personal data, server-side only: in the pipeline schema, out of the API's reach.
create table if not exists pipeline.profiles (
  id text primary key,
  answers jsonb not null,
  profile jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists pipeline.soirees (
  id text primary key,  -- the page's name: soiree-<random>-<wishes>, or <day>-<random> from the command line
  requests jsonb not null,  -- the evenings asked (surprise.parcours.Request): day, hours, budget, vibes, refusals…
  naming integer not null default 0,  -- routes still waiting for Claude's titles
  created_at timestamptz not null default now(),
  saved_at timestamptz not null default now()
);

create table if not exists pipeline.soiree_routes (
  soiree_id text not null references pipeline.soirees (id) on delete cascade,
  route integer not null,  -- 0, 1, 2: the routes proposed
  request integer,  -- its evening in soirees.requests, when several are planned together
  title text not null,
  pitch text not null,
  score double precision not null,
  primary key (soiree_id, route)
);

create table if not exists pipeline.soiree_steps (
  id bigint generated by default as identity primary key,
  soiree_id text not null references pipeline.soirees (id) on delete cascade,
  route integer not null,
  position integer not null,  -- order in the route; the night, when they sleep out, comes last
  source_id text not null,
  external_id text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  night boolean not null default false,
  step jsonb not null,  -- the step as composed (surprise.parcours.Step): the activity as it was then, travel
  created_at timestamptz not null default now(),
  replaced_at timestamptz,  -- drawn again: another activity took its place
  foreign key (source_id, external_id) references pipeline.normalized (source_id, external_id)
);
create unique index if not exists soiree_steps_current_idx on pipeline.soiree_steps (soiree_id, route, position) where replaced_at is null;
create index if not exists soiree_steps_activity_idx on pipeline.soiree_steps (source_id, external_id);
